FROM --platform=linux/amd64 ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

ARG WINE_VERSION=winehq-staging
ARG PYTHON_VERSION=3.7.5
ARG PYINSTALLER_VERSION=3.6

RUN set -x \
    && if [ "$(dpkg --print-architecture)" = "amd64" ]; then dpkg --add-architecture i386; fi \
    && apt-get update -qy \
    && apt-get install --no-install-recommends -qfy \
        apt-transport-https \
        ca-certificates \
        gnupg \
        software-properties-common \
        wget \
    && mkdir -p /etc/apt/keyrings \
    && wget -nv -O /etc/apt/keyrings/winehq-archive.key https://dl.winehq.org/wine-builds/winehq.key \
    && echo "deb [signed-by=/etc/apt/keyrings/winehq-archive.key] https://dl.winehq.org/wine-builds/ubuntu/ jammy main" > /etc/apt/sources.list.d/winehq.list \
    && apt-get update -qy \
    && apt-get install --no-install-recommends -qfy $WINE_VERSION winbind cabextract \
    && apt-get clean \
    && wget -nv https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks \
    && chmod +x winetricks \
    && mv winetricks /usr/local/bin

# wine settings
ENV WINEARCH win64
ENV WINEDEBUG fixme-all
ENV WINEPREFIX /wine



# # install python in wine, using the msi packages to install, extracting
# # the files directly, since installing isn't running correctly.
# RUN set -x \
#     && winetricks win7 \
#     && for msifile in `echo core dev exe lib path pip tcltk tools`; do \
#         wget -nv "https://www.python.org/ftp/python/$PYTHON_VERSION/amd64/${msifile}.msi"; \
#         wine msiexec /i "${msifile}.msi" /qb TARGETDIR=C:/Python37; \
#         rm ${msifile}.msi; \
#     done \
#     && cd /wine/drive_c/Python37 \
#     && echo 'wine '\''C:\Python37\python.exe'\'' "$@"' > /usr/bin/python \
#     && echo 'wine '\''C:\Python37\Scripts\easy_install.exe'\'' "$@"' > /usr/bin/easy_install \
#     && echo 'wine '\''C:\Python37\Scripts\pip.exe'\'' "$@"' > /usr/bin/pip \
#     && echo 'wine '\''C:\Python37\Scripts\pyinstaller.exe'\'' "$@"' > /usr/bin/pyinstaller \
#     && echo 'wine '\''C:\Python37\Scripts\pyupdater.exe'\'' "$@"' > /usr/bin/pyupdater \
#     && echo 'assoc .py=PythonScript' | wine cmd \
#     && echo 'ftype PythonScript=c:\Python37\python.exe "%1" %*' | wine cmd \
#     && while pgrep wineserver >/dev/null; do echo "Waiting for wineserver"; sleep 1; done \
#     && chmod +x /usr/bin/python /usr/bin/easy_install /usr/bin/pip /usr/bin/pyinstaller /usr/bin/pyupdater \
#     && (pip install -U pip || true) \
#     && rm -rf /tmp/.wine-*

# ENV W_DRIVE_C=/wine/drive_c
# ENV W_WINDIR_UNIX="$W_DRIVE_C/windows"
# ENV W_SYSTEM64_DLLS="$W_WINDIR_UNIX/system32"
# ENV W_TMP="$W_DRIVE_C/windows/temp/_$0"

# # install Microsoft Visual C++ Redistributable for Visual Studio 2017 dll files
# RUN set -x \
#     && rm -f "$W_TMP"/* \
#     && wget -P "$W_TMP" https://download.visualstudio.microsoft.com/download/pr/11100230/15ccb3f02745c7b206ad10373cbca89b/VC_redist.x64.exe \
#     && cabextract -q --directory="$W_TMP" "$W_TMP"/VC_redist.x64.exe \
#     && cabextract -q --directory="$W_TMP" "$W_TMP/a10" \
#     && cabextract -q --directory="$W_TMP" "$W_TMP/a11" \
#     && cd "$W_TMP" \
#     && rename 's/_/\-/g' *.dll \
#     && cp "$W_TMP"/*.dll "$W_SYSTEM64_DLLS"/
