#!/bin/sh
set -eu

HERE="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
ROOT="$(cd "$HERE/.." && pwd)"

LOADER="$ROOT/lib/ld-linux-aarch64.so.1"
LIBDIR="$ROOT/lib"
REALPY="$HERE/python3.14"

exec "$LOADER" --library-path "$LIBDIR" "$REALPY" "$@"
